spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:first-come-event
    username: sa
    password:
    hikari:
      minimum-idle: 50         # ???: 10, ?? ?? ??? ?
      maximum-pool-size: 50    # ???: 10, ?? ??? ?
      idle-timeout: 600000     # ???: 600000 (10?), ?? ???? ??? ??????? ?? (???)
      max-lifetime: 1800000    # ???: 1800000 (30?), ???? ??? ??????? ?? ?? (???)
      connection-timeout: 30000  # ???: 30000 (30?), ???? ?? ?? ???? ?? ?? (???)
      validation-timeout: 5000 # ???: 5000 (5?), ??? ??? ??? ?? ?? ?? (???)
      leak-detection-threshold: 0 # ???: 0 (????), ??? ?? ??? ?? ?? (???)

server:
  port: 8080 # ???: 8080, ?? ??
  servlet:
    context-path: / # ???: /, ???? ??
  tomcat:
    max-threads: 200 # ???: 200, ?? ??? ??? ?
    min-spare-threads: 10 # ???: 10, ?? ?? ??? ?
    connection-timeout: 20000 # ???: 20000 (20?), ??? ???? (???)
    accept-count: 100 # ???: 100, ?? ?? ??? ?
    max-connections: 10000 # ???: 10000, ?? ??? ?
    max-http-header-size: 8192 # ???: 8192 (8KB), ?? HTTP ?? ?? (???)
  compression:
    enabled: true # ???: false, ?? ??? ??
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # ???: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json, ??? MIME ??
    min-response-size: 2048 # ???: 2048 (2KB), ??? ?? ?? ?? (???)
